# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Fhl\PythonStudy\Python_Homework\JosephRing\src\UI\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 616)
        self.start = QtWidgets.QPushButton(MainWindow)
        self.start.setGeometry(QtCore.QRect(390, 480, 131, 41))
        self.start.setObjectName("start")
        self.close = QtWidgets.QPushButton(MainWindow)
        self.close.setGeometry(QtCore.QRect(550, 480, 131, 41))
        self.close.setObjectName("close")
        self.result_show = QtWidgets.QTextBrowser(MainWindow)
        self.result_show.setGeometry(QtCore.QRect(50, 330, 256, 192))
        self.result_show.setObjectName("result_show")
        self.label_result = QtWidgets.QLabel(MainWindow)
        self.label_result.setGeometry(QtCore.QRect(150, 310, 54, 12))
        self.label_result.setObjectName("label_result")
        self.label_start = QtWidgets.QLabel(MainWindow)
        self.label_start.setGeometry(QtCore.QRect(390, 410, 54, 12))
        self.label_start.setObjectName("label_start")
        self.label_step = QtWidgets.QLabel(MainWindow)
        self.label_step.setGeometry(QtCore.QRect(390, 440, 54, 12))
        self.label_step.setObjectName("label_step")
        self.line_step = QtWidgets.QLineEdit(MainWindow)
        self.line_step.setGeometry(QtCore.QRect(450, 440, 71, 20))
        self.line_step.setObjectName("line_step")
        self.line_start = QtWidgets.QLineEdit(MainWindow)
        self.line_start.setGeometry(QtCore.QRect(450, 410, 71, 20))
        self.line_start.setObjectName("line_start")
        self.button_choose = QtWidgets.QPushButton(MainWindow)
        self.button_choose.setGeometry(QtCore.QRect(350, 340, 131, 41))
        self.button_choose.setObjectName("button_choose")
        self.label_show = QtWidgets.QLabel(MainWindow)
        self.label_show.setGeometry(QtCore.QRect(140, 50, 54, 12))
        self.label_show.setObjectName("label_show")
        self.file_show = QtWidgets.QTextBrowser(MainWindow)
        self.file_show.setGeometry(QtCore.QRect(50, 70, 256, 192))
        self.file_show.setObjectName("file_show")
        self.button_conf = QtWidgets.QPushButton(MainWindow)
        self.button_conf.setGeometry(QtCore.QRect(550, 410, 131, 41))
        self.button_conf.setObjectName("button_conf")
        self.file_input = QtWidgets.QTextEdit(MainWindow)
        self.file_input.setGeometry(QtCore.QRect(440, 70, 251, 191))
        self.file_input.setObjectName("file_input")
        self.label_input = QtWidgets.QLabel(MainWindow)
        self.label_input.setGeometry(QtCore.QRect(530, 50, 54, 12))
        self.label_input.setObjectName("label_input")
        self.button_write = QtWidgets.QPushButton(MainWindow)
        self.button_write.setGeometry(QtCore.QRect(630, 340, 131, 41))
        self.button_write.setObjectName("button_write")
        self.button_read = QtWidgets.QPushButton(MainWindow)
        self.button_read.setGeometry(QtCore.QRect(500, 340, 111, 41))
        self.button_read.setObjectName("button_read")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "约瑟夫环UI"))
        self.start.setText(_translate("MainWindow", "START"))
        self.close.setText(_translate("MainWindow", "END"))
        self.label_result.setText(_translate("MainWindow", "结果显示"))
        self.label_start.setText(_translate("MainWindow", "起始位置"))
        self.label_step.setText(_translate("MainWindow", "步长设置"))
        self.button_choose.setText(_translate("MainWindow", "选择文件"))
        self.label_show.setText(_translate("MainWindow", "文件内容"))
        self.button_conf.setText(_translate("MainWindow", "设置完毕"))
        self.label_input.setText(_translate("MainWindow", "文件输入"))
        self.button_write.setText(_translate("MainWindow", "写入文件"))
        self.button_read.setText(_translate("MainWindow", "读取文件"))
